### PR TITLE
Added ho. mobile APN

### PR DESCRIPTION
**Pull request by PierreV2002**
Hi, I added italian MVNO "ho. mobile" APN. Hoping maintainers will merge it

### CODE REVIEW

**Comment by ItzLevvie** [comment]
Hey there, @PierreV2002!

This is a reply, to let you know that LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, I also suggest you take
a look at https://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Comment by ItzLevvie** [comment]
Hey there, @PierreV2002!

This is a reply, to let you know that LineageOS doesn't merge pull
requests submitted directly to their github.com repositories.

You can submit your change requests through their public review system,
located at https://review.lineageos.org/

That review system is an installation of Google's Gerrit code review.
If you've never interacted with Gerrit before, I also suggest you take
a look at https://wiki.lineageos.org/usinggerrit-howto.html

Thanks!

**Comment by nift4** [comment]
It will be NEVER merged because you have to submit it via https://review.LineageOS.org and not via GitHub

**Comment by haggertk** [comment]
Code changes to LineageOS are submitted through Gerrit - https://wiki.lineageos.org/how-to/submitting-patches

**Pull request closed without merging**
